CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `symbol` text,
  `exchange` text,
  `trade date` date DEFAULT NULL,
  `adjusted stock close price` double DEFAULT NULL,
  `option symbol` text,
  `expiration` date DEFAULT NULL,
  `strike` double DEFAULT NULL,
  `call/put` text,
  `style` text,
  `ask` double DEFAULT NULL,
  `bid` double DEFAULT NULL,
  `mean price` double DEFAULT NULL,
  `iv` double DEFAULT NULL,
  `volume` int(11) DEFAULT NULL,
  `open interest` int(11) DEFAULT NULL,
  `stock price for iv` double DEFAULT NULL,
  `*` text,
  `delta` double DEFAULT NULL,
  `vega` double DEFAULT NULL,
  `gamma` double DEFAULT NULL,
  `theta` double DEFAULT NULL,
  `rho` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_eem_trade_date` (`trade date`),
  KEY `idx_eem_expiration` (`expiration`)
) ENGINE=InnoDB AUTO_INCREMENT=295979 DEFAULT CHARSET=utf8;
